# Generated by Django 6.0.4 on 2026-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogSincronizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("pacientes", "Pacientes"),
                            ("medicamentos", "Medicamentos"),
                            ("procedimentos", "Procedimentos"),
                            ("hospital", "Hospital"),
                            ("medicos", "Médicos"),
                            ("financeiro", "Financeiro"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("ultima_sincronizacao", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="Sucesso", max_length=20)),
                ("registros_processados", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Log de Sincronização",
                "verbose_name_plural": "Logs de Sincronização",
            },
        ),
    ]
