# Generated by Django 6.0.6 on 2026-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integracoes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logsincronizacao",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("dim_tempo", "Dimensão: Tempo"),
                    ("dim_unidade", "Dimensão: Unidade"),
                    ("dim_paciente", "Dimensão: Paciente"),
                    ("dim_medicamento", "Dimensão: Medicamento"),
                    ("dim_tipo_procedimento", "Dimensão: Tipo Procedimento"),
                    ("dim_equipamento", "Dimensão: Equipamento"),
                    ("dim_protocolo", "Dimensão: Protocolo"),
                    ("dim_medico", "Dimensão: Médico"),
                    ("dim_convenio", "Dimensão: Convênio"),
                    ("fato_atendimentos", "Fato: Atendimentos"),
                    ("fato_estoque", "Fato: Estoque"),
                    ("fato_erros_medicao", "Fato: Erros de Medicação"),
                    ("fato_procedimentos", "Fato: Procedimentos"),
                    ("fato_infraestrutura", "Fato: Infraestrutura"),
                    ("fato_higienizacao", "Fato: Higienização"),
                    ("fato_desempenho_clinico", "Fato: Desempenho Clínico"),
                    ("fato_escala_medica", "Fato: Escala Médica"),
                    ("fato_financeiro", "Fato: Financeiro"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
