# Generated by Django 6.0.4 on 2026-04-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimPaciente",
            fields=[
                ("id_paciente", models.AutoField(primary_key=True, serialize=False)),
                ("pontuacao_nps", models.IntegerField()),
                ("faixa_etaria", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DimTempo",
            fields=[
                ("id_tempo", models.AutoField(primary_key=True, serialize=False)),
                ("data_registro", models.DateField()),
                ("mes", models.IntegerField()),
                ("ano", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DimUnidade",
            fields=[
                ("id_unidade", models.AutoField(primary_key=True, serialize=False)),
                ("nome_unidade", models.CharField(max_length=255)),
                ("tipo_leito", models.CharField(max_length=100)),
                ("capacidade_maxima", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FatoAtendimentos",
            fields=[
                ("id_atendimento", models.AutoField(primary_key=True, serialize=False)),
                ("tempo_permanencia_dias", models.IntegerField()),
                ("status_alta", models.CharField(max_length=100)),
                ("reinternacao_30d", models.BooleanField()),
                (
                    "id_paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimpaciente",
                    ),
                ),
                (
                    "id_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimtempo",
                    ),
                ),
                (
                    "id_unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimunidade",
                    ),
                ),
            ],
        ),
    ]
