# Generated by Django 6.0.4 on 2026-04-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimMedicamento",
            fields=[
                ("id_medicamento", models.AutoField(primary_key=True, serialize=False)),
                ("nome_farmaco", models.CharField(max_length=255)),
                ("classe_terapeutica", models.CharField(max_length=100)),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("item_essencial", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Dimensão Medicamento",
                "verbose_name_plural": "Dimensões Medicamento",
            },
        ),
        migrations.AlterModelOptions(
            name="dimpaciente",
            options={
                "verbose_name": "Dimensão Paciente",
                "verbose_name_plural": "Dimensões Paciente",
            },
        ),
        migrations.AlterModelOptions(
            name="dimtempo",
            options={
                "verbose_name": "Dimensão Tempo",
                "verbose_name_plural": "Dimensões Tempo",
            },
        ),
        migrations.AlterModelOptions(
            name="dimunidade",
            options={
                "verbose_name": "Dimensão Unidade",
                "verbose_name_plural": "Dimensões Unidade",
            },
        ),
        migrations.AlterModelOptions(
            name="fatoatendimentos",
            options={
                "verbose_name": "Fato Atendimento",
                "verbose_name_plural": "Fato Atendimentos",
            },
        ),
        migrations.CreateModel(
            name="FatoErrosMedicao",
            fields=[
                ("id_evento", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_erro", models.CharField(max_length=100)),
                ("severidade", models.CharField(max_length=50)),
                (
                    "id_medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimmedicamento",
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimpaciente",
                    ),
                ),
                (
                    "id_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimtempo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Erro Medicação",
                "verbose_name_plural": "Fato Erros Medicação",
            },
        ),
        migrations.CreateModel(
            name="FatoEstoque",
            fields=[
                (
                    "id_movimentacao",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quantidade_saida", models.FloatField()),
                ("saldo_atual", models.FloatField()),
                (
                    "id_medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimmedicamento",
                    ),
                ),
                (
                    "id_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimtempo",
                    ),
                ),
                (
                    "id_unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimunidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Estoque",
                "verbose_name_plural": "Fato Estoque",
            },
        ),
    ]
