# Generated by Django 6.0.4 on 2026-04-29 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicadores", "0002_dimmedicamento_alter_dimpaciente_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimEquipamento",
            fields=[
                ("id_equipamento", models.AutoField(primary_key=True, serialize=False)),
                ("nome_maquina", models.CharField(max_length=255)),
                ("modelo", models.CharField(max_length=100)),
                ("ultima_manutencao", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Dimensão Equipamento",
                "verbose_name_plural": "Dimensões Equipamento",
            },
        ),
        migrations.CreateModel(
            name="DimTipoProcedimento",
            fields=[
                (
                    "id_tipo_procedimento",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nome_procedimento", models.CharField(max_length=255)),
                ("especialidade", models.CharField(max_length=100)),
                ("valor_base", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Dimensão Tipo Procedimento",
                "verbose_name_plural": "Dimensões Tipo Procedimento",
            },
        ),
        migrations.CreateModel(
            name="FatoProcedimentos",
            fields=[
                (
                    "id_procedimento_instancia",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("tempo_preparo_minutos", models.FloatField()),
                ("tempo_execucao_minutos", models.FloatField()),
                ("tempo_limpeza_minutos", models.FloatField()),
                ("status_agendamento", models.CharField(max_length=50)),
                (
                    "id_equipamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="indicadores.dimequipamento",
                    ),
                ),
                (
                    "id_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimtempo",
                    ),
                ),
                (
                    "id_tipo_procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimtipoprocedimento",
                    ),
                ),
                (
                    "id_unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimunidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Procedimento",
                "verbose_name_plural": "Fato Procedimentos",
            },
        ),
    ]
