# Generated by Django 6.0.4 on 2026-04-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicadores", "0003_dimequipamento_dimtipoprocedimento_fatoprocedimentos"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatoHigienizacao",
            fields=[
                (
                    "id_higienizacao",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("data_hora_saida_paciente", models.DateTimeField()),
                ("data_hora_liberacao_leito", models.DateTimeField()),
                (
                    "id_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimtempo",
                    ),
                ),
                (
                    "id_unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimunidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Higienização",
                "verbose_name_plural": "Fato Higienização",
            },
        ),
        migrations.CreateModel(
            name="FatoInfraestrutura",
            fields=[
                ("id_registro", models.AutoField(primary_key=True, serialize=False)),
                ("consumo_agua_m3", models.FloatField()),
                ("consumo_energia_kwh", models.FloatField()),
                ("total_colaboradores_ativos", models.IntegerField()),
                ("eventos_infeccao", models.IntegerField()),
                (
                    "id_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimtempo",
                    ),
                ),
                (
                    "id_unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimunidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Infraestrutura",
                "verbose_name_plural": "Fato Infraestrutura",
            },
        ),
    ]
