# Generated by Django 6.0.4 on 2026-04-29 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicadores", "0004_fatohigienizacao_fatoinfraestrutura"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimMedico",
            fields=[
                ("id_medico", models.AutoField(primary_key=True, serialize=False)),
                ("nome_medico", models.CharField(max_length=255)),
                ("especialidade", models.CharField(max_length=100)),
                ("crm", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Dimensão Médico",
                "verbose_name_plural": "Dimensões Médico",
            },
        ),
        migrations.CreateModel(
            name="DimProtocolo",
            fields=[
                ("id_protocolo", models.AutoField(primary_key=True, serialize=False)),
                ("nome_protocolo", models.CharField(max_length=255)),
                ("area_medica", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Dimensão Protocolo",
                "verbose_name_plural": "Dimensões Protocolo",
            },
        ),
        migrations.CreateModel(
            name="FatoDesempenhoClinico",
            fields=[
                ("id_registro", models.AutoField(primary_key=True, serialize=False)),
                ("aderente_ao_protocolo", models.BooleanField(default=True)),
                ("tempo_fechamento_prontuario_min", models.FloatField()),
                (
                    "id_medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimmedico",
                    ),
                ),
                (
                    "id_protocolo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimprotocolo",
                    ),
                ),
                (
                    "id_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimtempo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Desempenho Clínico",
                "verbose_name_plural": "Fato Desempenho Clínico",
            },
        ),
        migrations.CreateModel(
            name="FatoEscalaMedica",
            fields=[
                ("id_escala", models.AutoField(primary_key=True, serialize=False)),
                ("status_presenca", models.CharField(max_length=50)),
                ("horas_atraso", models.FloatField(default=0)),
                (
                    "id_medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimmedico",
                    ),
                ),
                (
                    "id_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimtempo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Escala Médica",
                "verbose_name_plural": "Fato Escalas Médicas",
            },
        ),
    ]
