# Generated by Django 6.0.4 on 2026-04-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicadores", "0005_dimmedico_dimprotocolo_fatodesempenhoclinico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimConvenio",
            fields=[
                ("id_convenio", models.AutoField(primary_key=True, serialize=False)),
                ("nome_operadora", models.CharField(max_length=255)),
                ("tipo_contrato", models.CharField(max_length=100)),
                ("prazo_contratual_pagamento", models.IntegerField()),
            ],
            options={
                "verbose_name": "Dimensão Convênio",
                "verbose_name_plural": "Dimensões Convênio",
            },
        ),
        migrations.CreateModel(
            name="FatoFinanceiro",
            fields=[
                ("id_transacao", models.AutoField(primary_key=True, serialize=False)),
                ("receita_bruta", models.FloatField()),
                ("valor_glosa_inicial", models.FloatField()),
                ("valor_glosa_recuperada", models.FloatField()),
                ("custos_operacionais", models.FloatField()),
                ("data_pagamento_prevista", models.DateField()),
                ("data_pagamento_real", models.DateField(blank=True, null=True)),
                (
                    "id_convenio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimconvenio",
                    ),
                ),
                (
                    "id_tempo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimtempo",
                    ),
                ),
                (
                    "id_unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicadores.dimunidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Financeiro",
                "verbose_name_plural": "Fato Financeiro",
            },
        ),
    ]
