# Generated by Django 6.0.6 on 2026-06-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicadores", "0006_dimconvenio_fatofinanceiro"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoConhecimento",
            fields=[
                ("id_documento", models.AutoField(primary_key=True, serialize=False)),
                ("nome_arquivo", models.CharField(max_length=255)),
                ("tipo_documento", models.CharField(max_length=50)),
                ("tamanho_bytes", models.IntegerField()),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                ("conteudo_completo", models.TextField()),
            ],
            options={
                "verbose_name": "Documento de Conhecimento",
                "verbose_name_plural": "Documentos de Conhecimento",
            },
        ),
        migrations.CreateModel(
            name="ResumoExecutivo",
            fields=[
                ("id_resumo", models.AutoField(primary_key=True, serialize=False)),
                ("data_geracao", models.DateField(auto_now_add=True)),
                ("dados_anomalias", models.JSONField()),
                ("conteudo_resumo", models.TextField()),
            ],
            options={
                "verbose_name": "Resumo Executivo",
                "verbose_name_plural": "Resumos Executivos",
            },
        ),
        migrations.CreateModel(
            name="BlocoDocumento",
            fields=[
                ("id_bloco", models.AutoField(primary_key=True, serialize=False)),
                ("indice_bloco", models.IntegerField()),
                ("conteudo", models.TextField()),
                ("embedding", models.JSONField(blank=True, null=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocos",
                        to="indicadores.documentoconhecimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloco de Documento",
                "verbose_name_plural": "Blocos de Documentos",
            },
        ),
    ]
